import type { Metadata } from "next";
import { Onest } from 'next/font/google'
import "./globals.css";
import LenisProvider from "@/app/LenisProvider";


const onest = Onest({
    variable: "--font-onest",
    subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} antialiased`}
      >
      <LenisProvider />
        {children}
      </body>
    </html>
  );
}
